POST http://localhost:3001/api/registrarEstudiante
Content-Type: application/json

{"nombre": "ana","celular":3159273187,"institucion":"salesiano","apellido": "beltran","correo": "anasobeltran@gmail.com","correoAcudiente":"lmrmillan@hotmail.com","contrasena": "1234","targetaId": 1004716847}