PUT http://localhost:3001/api/cambiarJuego/crearPregunta/ana
Content-Type: application/json

{"question": {"numPregunta":1,"pregunta":"primera pregunta","respuesta":1,"posiblesRespuestas":["es ...","tal vez...","podria ser..."]}}